# Generated by Django 5.1.1 on 2025-04-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='時間割のタイトル')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='授業名')),
                ('weekday', models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日'), ('日', '日曜日')], max_length=2, verbose_name='曜日')),
                ('period', models.CharField(choices=[('1', '1限'), ('2', '2限'), ('3', '3限'), ('4', '4限'), ('5', '5限'), ('6', '6限'), ('7', '7限')], max_length=1, verbose_name='時限')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='教室')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='教員')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetable', verbose_name='時間割')),
            ],
            options={
                'unique_together': {('timetable', 'weekday', 'period')},
            },
        ),
    ]
