# Generated by Django 5.1.1 on 2025-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classentry',
            name='period',
            field=models.CharField(choices=[('1', '1限'), ('2', '2限'), ('3', '3限'), ('4', '4限'), ('5', '5限'), ('6', '6限')], max_length=1, verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='classentry',
            name='weekday',
            field=models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日')], max_length=2, verbose_name='曜日'),
        ),
    ]
